.TH WATCH-FOR-INTERNET 1 "June 24, 2012"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
watch-for-internet \- program to continually connect to the internet
.SH SYNOPSIS
.B watch-for-internet
.br
.SH DESCRIPTION
This manual page documents briefly the
.B watch-for-internet
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBwatch-for-internet\fP is a program that tries continually connecting to the
internet via a connected USB Cell Modem.
.SH OPTIONS
This program does not accept command line arguments.
.SH FILES
.B /etc/watch_for_internet.conf
All configuration is done here.
.br
.SH AUTHOR
watch-for-internet was written by Philip J Freeman <philip.freeman@gmail.com>.
.PP
This manual page was written by Philip J Freeman <philip.freeman@gmail.com>,
for the Debian project (and may be used by others).
