.TH WATCH4INET 1 "June 24, 2012"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
watch4inet \- program to continually connect to the internet
.SH SYNOPSIS
.B watch4inet
.br
.SH DESCRIPTION
This manual page documents briefly the
.B watch4inet
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBwatch4inet\fP is a program that tries continually connecting to the
internet via a connected USB Cell Modem.
.SH OPTIONS
This program does not accept command line arguments.
.SH FILES
.B /etc/watch4inet.conf
All configuration is done here.
.br
.SH AUTHOR
watch4inet was written by Philip J Freeman <philip.freeman@gmail.com>.
.PP
This manual page was written by Philip J Freeman <philip.freeman@gmail.com>,
for the Debian project (and may be used by others).
